### ISSUE TITLE
Addon don't start, exceptions

### ISSUE THREAD

**Issue by cvermot** [WiwiWillou/tydom2mqtt#33]
Hi every body,

My addon was working fine. But after updating the addon from 0.99 to 1.01, it didn't work anymore...
I get this erros in the addon log :
` File "/opt/tydom2mqtt/tydomConnector.py", line 120, in connect
    self.connection = await websockets.client.connect('wss://{}:443/mediation/client?mac={}&appli=1'.format(self.host, self.mac),
  File "/usr/lib/python3.8/site-packages/websockets/imports.py", line 96, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
STARTING TYDOM2MQTT
Dectecting environnement......
/data/options.json detected ! Hassio Addons Environnement : parsing options.json....
{'TYDOM_MAC': 'myTydomMac', 'TYDOM_IP': '192.168.1.116', 'TYDOM_PASSWORD': 'MyTydomPassword', 'TYDOM_ALARM_PIN': 123456, 'TYDOM_ALARM_HOME_ZONE': 1, 'TYDOM_ALARM_NIGHT_ZONE': 2, 'MQTT_HOST': 'localhost', 'MQTT_USER': 'mqttuser', 'MQTT_PASSWORD': 'myMqttPassword', 'MQTT_PORT': 1883, 'MQTT_SSL': False, 'log_level': 'debug'}
Initialising TydomClient Class
Setting local mode context.
Starting main loop_task
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Attempting MQTT connection...
MQTT host :  localhost
MQTT user :  mqtt
##################################
Subscribing to :  +/tydom/#
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
TYDOM WEBSOCKET CONNECTION INITIALISING....                     
Building headers, getting 1st handshake and authentication....
Upgrading http connection to websocket....
Attempting websocket connection with tydom hub.......................
Host Target :
192.168.1.116
Starting /opt/tydom2mqtt/main.py
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<listen_tydom_forever() done, defined at /opt/tydom2mqtt/main.py:104> exception=AttributeError("module 'websockets' has no attribute 'client'")>
Traceback (most recent call last):
  File "/opt/tydom2mqtt/main.py", line 113, in listen_tydom_forever
    await tydom_client.connect()
  File "/opt/tydom2mqtt/tydomConnector.py", line 120, in connect
    self.connection = await websockets.client.connect('wss://{}:443/mediation/client?mac={}&appli=1'.format(self.host, self.mac),
  File "/usr/lib/python3.8/site-packages/websockets/imports.py", line 96, in __getattr__
    raise AttributeError(f"module {package!r} has no attribute {name!r}")
AttributeError: module 'websockets' has no attribute 'client'`

Addon version : 1.01
Mosquito Broker : 5.5.1
HA Core : core-2021.4.6
HA Supervisor : supervisor-2021.04.0
HA OS : Home Assistant OS 5.13

Thank you for your advices !

**Comment by cvermot** [comment]
Hi,

I looked about websockets. I think that some python dependencies have been updated to websockets 8.x to 9.0.
I found here : https://websockets.readthedocs.io/en/stable/changelog.html

> 9.0
> May 1, 2021
> 
> Note
> Version 9.0 moves or deprecates several APIs.
> 
> Aliases provide backwards compatibility for all previously public APIs.
> 
> Headers and MultipleValuesError were moved from websockets.http to websockets.datastructures. If you’re using them, you should adjust the import path.
> 
> The **client, server, protocol, and auth modules were moved from the websockets package to websockets.legacy** sub-package, as part of an upcoming refactoring. Despite the name, they’re still fully supported. The refactoring should be a transparent upgrade for most uses when it’s available. The legacy implementation will be preserved according to the backwards-compatibility policy.

So, I think we would have some impact on the code...

**Comment by mrwiwi** [comment]
Thanks for reporting, i've just commited a quick fix on addon base, could you try a rebuild pls ? (refresh addon store just to be sure)

**Comment by mrwiwi** [comment]
Found the issue, will post a fix soon

**Comment by mrwiwi** [comment]
Fixed, easy peasy lemon squeezy for that one ^^

**Comment by cvermot** [comment]
Thank you for the quick fix ! It's work !

**Comment by Zatowa** [comment]
Hello, 
I have a same issue :

STARTING TYDOM2MQTT
Dectecting environnement......
/data/options.json detected ! Hassio Addons Environnement : parsing options.json....
{'TYDOM_MAC': '001A2505839E', 'TYDOM_IP': '192.168.1.43', 'TYDOM_PASSWORD': 'MyPassword', 'TYDOM_ALARM_PIN': 123456, 'TYDOM_ALARM_HOME_ZONE': 1, 'TYDOM_ALARM_NIGHT_ZONE': 2, 'MQTT_HOST': '192.168.1.42', 'MQTT_USER': 'myuser', 'MQTT_PASSWORD': 'myPassword', 'MQTT_PORT': 1883, 'MQTT_SSL': False, 'log_level': 'info'}
Initialising TydomClient Class
Setting local mode context.
Starting main loop_task
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Attempting MQTT connection...
MQTT host :  192.168.1.42
MQTT user :  mqtt-user
##################################
Subscribing to :  +/tydom/#
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
TYDOM WEBSOCKET CONNECTION INITIALISING....                     
Building headers, getting 1st handshake and authentication....
Upgrading http connection to websocket....
Attempting websocket connection with tydom hub.......................
Host Target :
192.168.1.43
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<listen_tydom_forever() done, defined at /opt/tydom2mqtt/main.py:104> exception=InvalidMessage('did not receive a valid HTTP response')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/websockets/legacy/client.py", line 134, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/lib/python3.8/site-packages/websockets/legacy/http.py", line 141, in read_response
    headers = await read_headers(stream)
  File "/usr/lib/python3.8/site-packages/websockets/legacy/http.py", line 169, in read_headers
    raise ValueError(f"invalid HTTP header line: {d(line)}") from None
ValueError: invalid HTTP header line:   realm="Protected Area",
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/tydom2mqtt/main.py", line 113, in listen_tydom_forever
    await tydom_client.connect()
  File "/opt/tydom2mqtt/tydomConnector.py", line 121, in connect
    self.connection = await websockets.connect('wss://{}:443/mediation/client?mac={}&appli=1'.format(self.host, self.mac),
  File "/usr/lib/python3.8/site-packages/websockets/legacy/client.py", line 649, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/site-packages/websockets/legacy/client.py", line 660, in __await_impl__
    await protocol.handshake(
  File "/usr/lib/python3.8/site-packages/websockets/legacy/client.py", line 321, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/lib/python3.8/site-packages/websockets/legacy/client.py", line 140, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
Starting /opt/tydom2mqtt/main.py

Addon version : release_1.2.1
Mosquito Broker : 6.0.1
HA Core : core-2021.11.1
HA Supervisor : supervisor-2021.10.8
HA OS : Home Assistant OS 5.10.17-v8

Thank you for your advices !

**Comment by Zatowa** [comment]
in the system logs :

```
21-11-08 20:00:42 WARNING (MainThread) [supervisor.api.middleware.security] 70812686_tydom2mqtt_hassio missing API permission for /host/info
21-11-08 20:00:42 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /host/info
21-11-08 20:00:44 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt-user'
21-11-08 20:00:45 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt-user'
21-11-08 20:05:45 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt-user'
21-11-08 20:05:45 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt-user'
```
